---
title: "Basic example stepping through EPP-ASM for key populations"
author: ""
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
editor_options: 
  chunk_output_type: console
---
  
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  comment = "#>"
)
library(data.table)
library(ggplot2)
```


```{r, load}

rm(list=ls())

devtools::install_github("mrc-ide/eppasm@new-master-csvar")
#devtools::install_github("jeffeaton/epp@deepa-dev")
devtools::load_all("~/epp")
devtools::load_all("~/eppasm")

spec_files = paste0("C:/Users/DeepaJahagirdar/Avenir Health Dropbox/Avenir Shared Drive/DataSets/UNAIDS/2022 Estimates/Public Spectrum Files/")


```

## Read in files

```{r, eppasm_inputs}

pjnz <- system.file("extdata/testpjnz", "senegal_2021_05_04.pjnz", package="eppasm")

pjnz <- paste0(spec_files, "Niger_2022_v2_22032022.pjnz")

#15-49 populations file by subpopulation - gets used in create_subpop_specfp
pops = epp::read_epp_subpops(pjnz)$subpops

#Entrant prevalences
entrantprev = readRDS(system.file("extdata/entrantprev.RDS", package="eppasm"))

##Population tag = <BigPop MV3>

```

## Prepare inputs for EPP-ASM

```{r eppasm_inputs}

loc <- prepare_spec_fit(pjnz, proj.end=2021.5, popupdate = FALSE, popadjust = FALSE, old=FALSE)
loc <- lapply(loc, function(x) { ##Not sure why these broke, will figure out later
  attr(x, "specfp")$entrantprev <- entrantprev
  return(x)})

```

## EPP-ASM model with single set of parameter inputs

Prepare model parameters from parameter vector input
```{r, single_param}
theta_ur  <- c( -3.415205e-01, -2.356644e+00, -1.869026e+00 , 2.002022e+03 ,-6.746011e-02 -8.147922e-02,9.314390e-04 , 3.151236e+00 ,-2.473241e-01, -3.274984e+00)


theta_ur = apply(readRDS("~/HIV/tests/NIGER_test1pop_fem.RDS")$`Pop féminine restante`$resample,2,mean)

theta_ur = apply(readRDS("~/HIV/tests/SEN_test2FSW.RDS")$`Travailleurs du sexe`$resample,2,mean)

fp <- attr(loc$`Pop féminine restante`, "specfp")
fp <- attr(loc$`Pop masculine restante`, "specfp")
fp <- attr(loc$`Travailleurs du sexe`, "specfp")

#time-varying omega, 2005-2020
omega = c(0.55,0.60,0.65,0.70,0.75,0.81,0.80,0.79,0.77,0.75,0.72,0.75,0.77,0.78,0.80,0.82)
fp$relinfectART_ts <-  array(0,length(unique(floor(fp$proj.steps))))
fp$relinfectART_ts[36:(dim(fp$entrantartcov)[2]-1)] <- (1-omega)
fp$relinfectART_ts[which(fp$relinfectART_ts == 0)] <- fp$relinfectART

#Using migration of 0 for key populations
fp$netmigr <- attr(loc$`Travailleurs du sexe`,"specfp")$netmigr - attr(loc$`Travailleurs du sexe`,"specfp")$netmigr

fp <- prepare_rhybrid(fp)
fp$logitiota <- TRUE
fp$incidmod <- "eppspectrum"
fp$popadjust <- FALSE
fp$epidemicType <- "concentrated"


param <- fnCreateParam(theta_ur, fp)
fp_par <- update(fp, list = param)


```

Simulate the model once.

```{r, simulate_model}
mod <- simmod.specfp(fp = fp_par, VERSION = "R")

inc1 <- apply(attr(mod,"infections"),3,sum) #TV omega
inc2 <- apply(attr(mod,"infections"),3,sum) #No TV
inc3 <- apply(attr(mod,"infections"),3,sum) #No ART

inc1a <-  attr(mod,"incid15to49")
inc2a <-  attr(mod,"incid15to49")
prev2 <-  apply(attr(mod,"hivpop"),4,sum)
plot(prev1[1:48],type="l")
lines(prev2[1:48],col="red")
plot(inc2[1:49],type="l")
lines(inc1[1:49],col="blue")
lines(inc3[1:49],col="red")

prev1 = data.table(indicator = "prevalence", simulation = c(rep("tv_omega",length(prev_w_tv_omega)*2),rep("omega",length(prev_w_tv_omega)*2)),
                   value = c(prev_w_tv_omega,prev_omega),
                   year = 1970:2021)

inc1 = data.table(indicator = "incidence", simulation = c(rep("tv_omega",length(prev_w_tv_omega)*2),rep("omega",length(prev_w_tv_omega)*2)), 
                  value = c(inc_w_tv_omega,inc_omega),
                   year = 1970:2021)

all = data.table(rbind(prev1,inc1))
ggplot(all[year < 2019],aes(x = year,value,col = simulation)) + geom_line() + facet_wrap(~indicator)

```


## Fitting the EPP-ASM model

```{r, fit_eppasm, cache=TRUE}

locfit = list()


##Because there are no women in these populations how could we use agepregprev function...
attr(loc$`HSH`,"specfp")$pregprev <- FALSE  
attr(loc$`Clients des travailleurs du sexe`,"specfp")$pregprev <- FALSE  
attr(loc$`Pop masculine restante`,"specfp")$pregprev <- FALSE  

##Adding this because they wound up NA, XML file missing string attribute
loc$`Clients des travailleurs du sexe`$fp$assignmentType <- 'replace'

theta_ur = apply(readRDS("~/HIV/tests/SEN_test1HSH.RDS")$`HSH`$resample,2,mean)
locfit$HSH <- eppasm::fitmod(loc$HSH, eppmod = "rhybrid", rw_start = 2005,B0=1e3, B=1e2, opt_iter = 1, number_k=250, optfit = TRUE, opthess=FALSE, opt_init = theta_ur)
saveRDS(locfit,"~/HIV/tests/NIGER_test1HSH.RDS")

theta_ur = apply(readRDS("~/HIV/tests/SEN_test2FSW.RDS")$`Travailleurs du sexe`$resample,2,mean)
locfit$`Travailleurs du sexe`<- eppasm::fitmod(loc$`Travailleurs du sexe`, eppmod = "rhybrid", rw_start = 2005,B0=1e3, B=1e2, opt_iter = 1, number_k=250, optfit = FALSE, opthess=FALSE, opt_init = theta_ur)
saveRDS(locfit,"~/HIV/tests/SEN_test2FSW.RDS")
#Test1: original
#Test2 : revise ART calculation

theta_ur = apply(readRDS("~/HIV/tests/SEN_test1CFSW.RDS")$`Clients des travailleurs du sexe`$resample,2,mean)
locfit$`Clients des travailleurs du sexe`<- eppasm::fitmod(loc$`Clients des travailleurs du sexe`, eppmod = "rhybrid",rw_start = 2005,B0=1e3, B=1e2, opt_iter = 1, number_k=250, optfit = TRUE,  opt_init = theta_ur, opthess=FALSE)
saveRDS(locfit,"~/HIV/tests/NIGER_test1CFSW.RDS")

theta_ur = apply(readRDS("~/HIV/tests/SEN_test1pop_fem.RDS")$`Pop féminine restante`$resample,2,mean)
locfit$`Pop féminine restante`<- eppasm::fitmod(loc$`Pop féminine restante`,  eppmod = "rhybrid",  rw_start = 2005,B0=1e3, B=1e2, opt_iter = 1, number_k=250, optfit = FALSE, opthess=FALSE,  opt_init = theta_ur)
saveRDS(locfit,"~/HIV/tests/NIGER_test1pop_fem.RDS")

theta_ur = apply(readRDS("~/HIV/tests/SEN_test1pop_masc.RDS")$`Pop masculine restante`$resample,2,mean)
locfit$`Pop masculine restante`<- eppasm::fitmod(loc$`Pop masculine restante`,  eppmod = "rhybrid", rw_start = 2005, B0=1e3, B=1e2, opt_iter = 1, number_k=250, optfit = TRUE,opthess=FALSE,  opt_init = theta_ur)
saveRDS(locfit,"~/HIV/tests/NIGER_test1pop_masc.RDS")

locfit$`Population carcerale`<- eppasm::fitmod(loc$`Population carcerale`,  eppmod = "rhybrid", rw_start = 2005, B0=1e3, B=1e2, opt_iter = 1, number_k=250, optfit = TRUE, opthess = FALSE, opt_init = theta_ur)
saveRDS(locfit,"~/HIV/tests/NIGER_test1pop_carc.RDS")



saveRDS(locfit, "~/HIV/tests/2023-04-09-NIGER.RDS")#Baseline
locfit = readRDS( "~/HIV/tests/2023-04-02-SEN.RDS")#Baseline



#saveRDS(locfit, "~/Documents/tests/SEN_test5fitmod_all.RDS") ##FSW only
#saveRDS(locfit, "~/Documents/tests/SEN_test6fitmod_all.RDS") ##HSH only
#saveRDS(locfit, "~/Documents/tests/SEN_test7fitmod_all.RDS") ##FSW with popadjust = FALSE
#saveRDS(locfit, "~/Documents/tests/SEN_test8fitmod_all.RDS") ##FSW with lower entrant numbers
#saveRDS(locfit, "~/Documents/tests/SEN_test9fitmod_all.RDS") ##FSW with no ANC data
#saveRDS(locfit, "~/Documents/tests/SEN_test10fitmod_all.RDS") ##Clients only
#saveRDS(locfit, "~/Documents/tests/SEN_test11fitmod_all.RDS") ##Pop fem restante
#saveRDS(locfit, "~/Documents/tests/SEN_test12fitmod_all.RDS") ##Pop masc restante
#saveRDS(locfit, "~/Documents/tests/SEN_test13fitmod_all.RDS") ##FSW with 16% growth rate
#saveRDS(locfit, "~/Documents/tests/SEN_test14fitmod_all.RDS") ##FSW with 16% growth and rspline
#saveRDS(locfit, "~/Documents/tests/SEN_test15fitmod_all.RDS") ##HSH with proper pop growth and rhybrid
#saveRDS(locfit, "~/Documents/tests/SEN_test16fitmod_all.RDS") ##All groups, rhbrid, proper pops and ART
#saveRDS(locfit, "~/Documents/tests/SEN_test17fitmod_all.RDS") ##FSW duration = 2, MSM duration = 30
#saveRDS(locfit, "~/Documents/tests/SEN_test18fitmod_all.RDS") ##HSH rspline
#saveRDS(locfit, "~/Documents/tests/SEN_test20fitmod_all.RDS") ##Clients, tighter anc prior
#saveRDS(locfit, "~/Documents/tests/SEN_test21fitmod_all.RDS") ##HSH, older age dist prior
#saveRDS(locfit, "~/Documents/tests/SEN_test22fitmod_all.RDS") ##HSH, rspline, eqprior
```

## Extend the projection

```{r, fit_eppasm, cache=TRUE}
#locfit = readRDS("~/Documents/tests/SEN_test19fitmod_all.RDS")
locfit = readRDS( "~/HIV/tests/2023-04-02-SEN.RDS")
locfit <- lapply(locfit, extend_projection, proj_years = 52, no_resample = T)


```

## Aggregation

```{r, fit_eppasm, cache=TRUE}
#Single sim uses a single theta victor- resulting in Nan- Instead, set to just take first 2 resamples for testing

##Adding this because they wound up NA, XML file missing string attribute
locfit$`Clients des travailleurs du sexe`$fp$assignmentType <- 'replace'
locfit$`Population carcerale`$fp$assignmentType <- 'replace'

##With incorporating turnover
g1 = calc_prev15to49(locfit$`Pop féminine restante`, fp = locfit$`Pop féminine restante`$fp)
g1 = calc_prev15to49(locfit$`Pop féminine restante`$mod, fp = locfit$`Pop féminine restante`$fp)


locfit_aggr <- aggr_specfit(fitlist=locfit, turnover = TRUE,  single_sim = T)

#saveRDS(locfit_aggr,"~/Documents/tests/SEN_test19fitmod_all_national.RDS")
locfit_aggr[[2]]
plot(attr(locfit_aggr[[2]][[2]][[1]],"prev15to49"))
plot(attr(locfit_aggr[[1]],"incid15to49"))


incid = colMeans(do.call(rbind,lapply(locfit_aggr[[1]],function(x) attr(x,"incid15to49"))))*100
incid = cbind(year = seq(1970, 1970 + length(incid)), incid = incid)


```
