---
title: "Basic example stepping through EPP-ASM for key populations"
author: ""
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
editor_options: 
  chunk_output_type: console
---
  
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  comment = "#>"
)
library(data.table)
library(ggplot2)
```


```{r, load}

rm(list=ls())

devtools::install_github("mrc-ide/eppasm@new-master-csvar")
#devtools::install_github("jeffeaton/epp@deepa-dev")
devtools::load_all("~/epp")
devtools::load_all("~/eppasm")


```

## Read in files

```{r, eppasm_inputs}

#INSERT FILEPATH
pjnz <- system.file("extdata/testpjnz/Niger_2022_v2_22032022.pjnz", package="eppasm")

#15-49 populations file by subpopulation - gets used in create_subpop_specfp
pops = epp::read_epp_subpops(pjnz)$subpops

#Entrant prevalences
entrantprev = readRDS(system.file("extdata/entrantprev.RDS", package="eppasm"))


```

## Prepare inputs for EPP-ASM

```{r eppasm_inputs}

loc <- prepare_spec_fit(pjnz, proj.end=2021.5, popupdate = FALSE, popadjust = FALSE, old=FALSE)
loc <- lapply(loc, function(x) { ##Not sure why these broke, will figure out later
  attr(x, "specfp")$entrantprev <- entrantprev
  return(x)})

```

## EPP-ASM model with single set of parameter inputs

Prepare model parameters from parameter vector input
```{r, single_param}
theta_ur  <- c( -0.80468221 ,  -3.05467714 ,  -0.92109689 ,1998.05761874  , -0.02347973  , -0.02034163  ,  1.78996904,  0.47265842  , -3.62173031)

fp = attr(loc$`Pop féminine restante`, "specfp")
fp <- prepare_rhybrid(fp)
fp$logitiota <- TRUE
fp$incidmod <- "eppspectrum"
fp$popadjust <- FALSE
fp$epidemicType <- "concentrated"


param <- fnCreateParam(theta_ur, fp)
fp_par <- update(fp, list = param)


```

Simulate the model once.

```{r, simulate_model}
mod <- simmod.specfp(fp = fp_par, VERSION = "R")

inc <- apply(attr(mod,"infections"),3,sum) 
inc1a <-  attr(mod,"incid15to49")
prev(mod)
incid(mod)

#Check against prevalence surveys
output = data.table(year = seq(1970,2021), incidence = incid(mod), prevalence = prev(mod))
output = melt(output, id.vars = "year")
output[,type := "model"]
surveys = attr(loc$`Pop féminine restante`,"eppd")
surveys = data.table(surveys$hhs)
surveys[,variable := "prevalence"]
surveys[,type := "survey"]

output = rbind(output, surveys[,.(year,type,value,variable)], use.names=T, fill=T)

ggplot(output) + geom_line(data = output[type == "model"], aes(year, value)) +
  geom_point(data = output[type == "survey"], aes(year, value), col="red") + 
  facet_wrap(~variable)

```


## Fitting the EPP-ASM model

```{r, fit_eppasm, cache=TRUE}

locfit = list()

##Because there are no women in these populations how could we use agepregprev function...
attr(loc$`HSH`,"specfp")$pregprev <- FALSE  
attr(loc$`Clients des travailleurs du sexe`,"specfp")$pregprev <- FALSE  
attr(loc$`Pop masculine restante`,"specfp")$pregprev <- FALSE  

##Adding this because they wound up NA, XML file missing string attribute
loc$`Clients des travailleurs du sexe`$fp$assignmentType <- 'replace'

locfit$HSH <- eppasm::fitmod(loc$HSH, eppmod = "rhybrid", rw_start = 2005,B0=1e3, B=1e2, opt_iter = 1, number_k=250, optfit = TRUE, opthess=FALSE, opt_init = theta_ur)

locfit$`Travailleurs du sexe`<- eppasm::fitmod(loc$`Travailleurs du sexe`, eppmod = "rhybrid", rw_start = 2005,B0=1e3, B=1e2, opt_iter = 1, number_k=250, optfit = FALSE, opthess=FALSE, opt_init = theta_ur)

locfit$`Clients des travailleurs du sexe`<- eppasm::fitmod(loc$`Clients des travailleurs du sexe`, eppmod = "rhybrid",rw_start = 2005,B0=1e3, B=1e2, opt_iter = 1, number_k=250, optfit = TRUE,  opt_init = theta_ur, opthess=FALSE)


locfit$`Pop féminine restante`<- eppasm::fitmod(loc$`Pop féminine restante`,  eppmod = "rhybrid",  rw_start = 2005,B0=1e5, B=1e2, opt_iter = 1, number_k=250, optfit = FALSE, opthess=FALSE,  opt_init = theta_ur)


locfit$`Pop masculine restante`<- eppasm::fitmod(loc$`Pop masculine restante`,  eppmod = "rhybrid", rw_start = 2005, B0=1e3, B=1e2, opt_iter = 1, number_k=250, optfit = TRUE,opthess=FALSE,  opt_init = theta_ur)


locfit$`Population carcerale`<- eppasm::fitmod(loc$`Population carcerale`,  eppmod = "rhybrid", rw_start = 2005, B0=1e3, B=1e2, opt_iter = 1, number_k=250, optfit = TRUE, opthess = FALSE, opt_init = theta_ur)



```

## Extend the projection

```{r, fit_eppasm, cache=TRUE}

locfit <- lapply(locfit, extend_projection, proj_years = 52, no_resample = T)


```

## Aggregation

```{r, fit_eppasm, cache=TRUE}
#Single sim uses a single theta victor- resulting in Nan- Instead, set to just take first 2 resamples for testing

##Adding this because they wound up NA, XML file missing string attribute
locfit$`Clients des travailleurs du sexe`$fp$assignmentType <- 'replace'
locfit$`Population carcerale`$fp$assignmentType <- 'replace'


locfit_aggr <- aggr_specfit(fitlist=locfit, turnover = TRUE,  single_sim = T)




```
