# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eppasmOO <- function(fp, MODEL = 1L, MIX = TRUE) {
    .Call('_eppasm_eppasmOO', PACKAGE = 'eppasm', fp, MODEL, MIX)
}

